local DocGenerator = {}

function DocGenerator.GenerateMarkdown(manifest, dependencyMap)
    print("[HERMES] DocGenerator: Producing Markdown documentation...")
    
    local doc = "# 📜 SAO ENGINE - ARCHITECTURE DOCUMENTATION\n"
    doc = doc .. "Generated by Hermes v5 on " .. os.date("%Y-%m-%d %H:%M:%S") .. "\n\n"
    
    doc = doc .. "## 🚀 Core Pillars (Shared)\n"
    for _, m in ipairs(manifest.SharedModules) do
        doc = doc .. string.format("### %s\n- **Path:** `%s`\n", m.Name, m.Path)
        local d = dependencyMap[m.Name]
        if d and #d.DependsOn > 0 then
            doc = doc .. "- **Dependencies:** " .. table.concat(d.DependsOn, ", ") .. "\n"
        end
        doc = doc .. "\n"
    end
    
    doc = doc .. "## 🛠️ Server Services\n"
    for _, s in ipairs(manifest.Services) do
        doc = doc .. string.format("- **%s** (`%s`)\n", s.Name, s.Path)
    end
    
    doc = doc .. "\n## 🎮 Client Controllers\n"
    for _, c in ipairs(manifest.Controllers) do
        doc = doc .. string.format("- **%s** (`%s`)\n", c.Name, c.Path)
    end
    
    return doc
end

return DocGenerator